### ISSUE TITLE
Is it possible to add views for github.io blog?

### ISSUE THREAD

**Issue by ShyRoute** [wesky93/views#2]
Is it possible to add views for github.io blog? I want to use it for github.io blog view counter (idea from [dwyl/hits](https://github.com/dwyl/hits) like this code).

```
<div style="text-align: center;">
  <img src="https://views.whatilearened.today/views/github/{{ site.url }}/{{ page.url }}.svg" alt="hit count image" />
</div>
```

Thank you for the great repo!

**Comment by wesky93** [comment]
Sure!
